

GET https://localhost:7100/catalog

###

GET http://localhost:5042/catalog

###

POST https://localhost:7100/catalog
Content-Type: application/json

{
    "name": "Shoes",
    "description": "Running Shoes",
    "brand": "Nike",
    "price": 109.99
}

DELETE https://localhost:7250/catalog/3

### GET token from Auth0
curl --request POST \
  --url https://dev-mrtgnxu2.us.auth0.com/oauth/token \
  --header 'content-type: application/json' \
  --data '{"client_id":"GCwbwpBnkNlbcLTXnCGUwC0HkFmrFV4D","client_secret":"MgqKBOAYQ1MbLHT7HGeATUmG78GOxm4xULjRVU7l2HMI9Rg1x3rZIyJz2j5XJkQO","audience":"https://project-4-life","grant_type":"client_credentials"}'
  