

GET https://localhost:7100/catalog

###

GET http://localhost:5042/catalog

###

POST https://localhost:7100/catalog
Content-Type: application/json

{
    "name": "Shoes",
    "description": "Running Shoes",
    "brand": "Nike",
    "price": 109.99
}


